# Generated by Django 3.1.3 on 2020-11-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Patient',
        ),
    ]
