# Generated by Django 3.1.3 on 2020-11-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.DateField(default='2000-1-1', null=True),
        ),
    ]
